/**
 * Example rulesync configuration.
 *
 * Copy this file to `rulesync.config.js` and tweak as needed. Every field is
 * optional — anything you omit falls back to the built-in defaults.
 *
 * @type {import('rulesync').RulesyncConfig}
 */
module.exports = {
  // Source-of-truth markdown file. Defaults to 'AGENTS.md'.
  source: 'AGENTS.md',

  // Toggle individual adapters on or off. Disabled adapters are skipped by
  // both `rulesync sync` and `rulesync check`.
  adapters: {
    claude: true,
    cursor: true,
    copilot: true,
    gemini: true,
    windsurf: true,
    cline: true,
    aider: false,
  },

  // Optional per-adapter header/footer wrappers. Useful for "do not edit"
  // banners or tool-specific front matter.
  overrides: {
    claude: {
      header: '<!-- Auto-generated by rulesync. Edit AGENTS.md to make changes. -->\n',
    },
    cursor: {
      footer: '\n# Synced by rulesync',
    },
  },
};
