import * as path from 'path';
import {
  fileExists,
  logger,
  readFileIfExists,
  resolvePath,
  writeFile,
} from '../utils';
import { ALL_ADAPTERS, defaultConfig } from '../config';
import { adapters as adapterRegistry, adapterPaths } from '../adapters';

/**
 * Default starter content for a fresh AGENTS.md.
 */
const STARTER_AGENTS_MD = `# Project rules for AI coding agents

## Project overview
Briefly describe what this project does and its tech stack.

## Coding conventions
- Use TypeScript strict mode.
- Prefer small, single-purpose functions.
- Write tests for any new behavior.

## What to avoid
- Do not introduce new dependencies without justification.
- Do not commit secrets, .env files, or large binaries.

## Useful commands
- \`npm run build\` — build the project
- \`npm test\` — run the test suite
`;

/**
 * Default rulesync.config.js scaffolded by `rulesync init`. We embed it as a
 * literal string so output formatting is predictable across editors.
 */
const STARTER_CONFIG = `/** @type {import('rulesync').RulesyncConfig} */
module.exports = {
  source: 'AGENTS.md',
  adapters: {
    claude: true,
    cursor: true,
    copilot: true,
    gemini: true,
    windsurf: true,
    cline: true,
    aider: false,
  },
  overrides: {
    claude: {
      header: '<!-- Auto-generated by rulesync. Edit AGENTS.md to make changes. -->\\n',
    },
  },
};
`;

/**
 * Find the first existing tool-specific rules file in the repo, returning
 * its path so we can use it as a seed for AGENTS.md. Order matches the
 * adapter registry.
 */
function detectExistingRuleFile(): { adapter: string; filePath: string } | null {
  for (const name of ALL_ADAPTERS) {
    const adapter = adapterRegistry[name];
    for (const p of adapterPaths(adapter)) {
      if (fileExists(resolvePath(p))) {
        return { adapter: name, filePath: p };
      }
    }
  }
  return null;
}

/**
 * Run the `rulesync init` command: scaffold AGENTS.md and rulesync.config.js,
 * seeding AGENTS.md from any existing rule file when possible.
 */
export async function runInit(): Promise<void> {
  const cfg = defaultConfig();
  const sourcePath = resolvePath(cfg.source);

  if (fileExists(sourcePath)) {
    logger.warn(`${cfg.source} already exists — leaving it untouched.`);
  } else {
    const existing = detectExistingRuleFile();
    if (existing) {
      const seed = readFileIfExists(resolvePath(existing.filePath)) ?? '';
      writeFile(sourcePath, seed);
      logger.success(
        `Scaffolded ${cfg.source} from existing ${existing.filePath} (${existing.adapter}).`,
      );
    } else {
      writeFile(sourcePath, STARTER_AGENTS_MD);
      logger.success(`Created starter ${cfg.source}.`);
    }
  }

  const cfgPath = resolvePath('rulesync.config.js');
  if (fileExists(cfgPath)) {
    logger.warn('rulesync.config.js already exists — leaving it untouched.');
  } else {
    writeFile(cfgPath, STARTER_CONFIG);
    logger.success('Created rulesync.config.js.');
  }

  logger.info(
    `\nNext: edit ${path.basename(cfg.source)} then run 'rulesync sync'.`,
  );
}
