import type { Adapter } from './index';

/**
 * Adapter that writes Aider's `.aider.conf.yml`. Aider's config is YAML, so
 * the source markdown is embedded as a multi-line `read` instruction value
 * along with a literal-block scalar containing the rules text.
 */
export const aiderAdapter: Adapter = {
  name: 'aider',
  outputPath: '.aider.conf.yml',
  render(source: string): string {
    const indented = source
      .split('\n')
      .map((line) => `  ${line}`)
      .join('\n');
    return `# Generated by rulesync. Edit AGENTS.md to make changes.\nlint: true\nauto-commits: false\nread: |\n${indented}\n`;
  },
};
